### ISSUE TITLE
az-101-03b__instructions.md lab error in task 1

### ISSUE THREAD

**Issue by brianpdk** [MicrosoftLearning/AZ-101-MicrosoftAzureIntegrationandSecurity#10]
If you are using a "Azure-pas – sponsorat" subscription your not allowed to deploy SQL i taks one unless you set the ressourcegroup location to "East US".

**Comment by polichtm** [comment]
I just created a SQL Database in WestUS2 in an Azure Pass (Sponsorship) subscription
rgds
Marcin

**Comment by brianpdk** [comment]
It worked with Canada Central but Central France, West Europe and East Europe same result:

{ "id": "/subscriptions/2dc8d145-7c28-4707-b18a-69c41319ab2d/resourceGroups/az1010301b-RG/providers/Microsoft.Resources/deployments/Microsoft.Template/operations/E90C71700ACFB07B", "operationId": "E90C71700ACFB07B", "properties": { "provisioningOperation": "Create", "provisioningState": "Failed", "timestamp": "2019-03-15T12:09:49.2810762Z", "duration": "PT1.9661969S", "trackingId": "4af2b54e-8469-40a8-b6a4-4a2f5beb3463", "serviceRequestId": "35a093c7-a12e-415e-bb9b-bd82314b2c6e", "statusCode": "Conflict", "statusMessage": { "status": "Failed", "error": { "code": "ResourceDeploymentFailure", "message": "The resource operation completed with terminal provisioning state 'Failed'.", "details": [ { "code": "ProvisioningDisabled", "**message": "Azure Benefits subscriptions are restricted from provisioning in this region. Please choose a different region. For exceptions to this rule please contact Microsoft Support.**" } ] } }, "targetResource": { "id": "/subscriptions/2dc8d145-7c28-4707-b18a-69c41319ab2d/resourceGroups/az1010301b-RG/providers/Microsoft.Sql/servers/sql1010301b3dmahrm6eohte", "resourceType": "Microsoft.Sql/servers", "resourceName": "sql1010301b3dmahrm6eohte" }, "request": { "content": { "location": "francecentral", "properties": { "administratorLogin": "Student", "administratorLoginPassword": "Pa55w.rd1234", "version": "12.0" } } }, "response": { "content": { "name": "35a093c7-a12e-415e-bb9b-bd82314b2c6e", "status": "Failed", "startTime": "2019-03-15T12:09:48.01Z", "error": { "code": "ProvisioningDisabled", "message": "Azure Benefits subscriptions are restricted from provisioning in this region. Please choose a different region. For exceptions to this rule please contact Microsoft Support." } } } }}

**Comment by polichtm** [comment]
To determine the availability of SQL Database in a target region, you can simply run:
Get-AzSqlCapability -LocationName location
and ensure that the status is reported as "Available"
rgds
Marcin
