### ISSUE TITLE
AZ-101-Mod 3-Lab Error

### ISSUE THREAD

**Issue by MohamedHoosen** [MicrosoftLearning/AZ-101-MicrosoftAzureIntegrationandSecurity#2]
Greetings

I am trying to complete the Lab for Module 3, Exercise 0 Task 1 end when click purchase, after some time provisioning deployment,  i get an error says deployment failed.
I used Labfiles --> from here  Allfiles/Labfiles

I have tried the with the SouthEastAsia & West US 2 data center

Please see below:

![001-2019-feb-18-003](https://user-images.githubusercontent.com/28430491/52960541-b4591900-33a1-11e9-866f-cc2d7e7cdcb7.jpg)

![001-2019-feb-18-004](https://user-images.githubusercontent.com/28430491/52960558-bd49ea80-33a1-11e9-9200-a05d6fe584dd.jpg)

![001-2019-feb-18-005](https://user-images.githubusercontent.com/28430491/52960564-c20e9e80-33a1-11e9-8776-39f86d398b40.jpg)

Please can you check and let me know if i had gone wrong somewhere?

Thanks

**Comment by polichtm** [comment]
Hi Mohamed,
I just tested this deployment and it completed successfully without any issues. 
Are you modifying any deployment parameters (other than the region) or are you accepting the ones imported from the parameters files?
hth
Marcin

**Comment by MohamedHoosen** [comment]
Hi Marcin

No im following exactly as the Lab Steps, the only changes i made as per lab
Image SKU: 2016-Datacenter-Server-Core

Im accepting ones from parameters file.

and is this correct Configuration Function: ContosoWebsite.ps1\\ContosoWebsite (with double \\)
because the default value is Configuration Function: ContosoWebsite.ps1\ContosoWebsite (with 1 \ )

Could is be because of my Azure Sponsorship Subscription has limitations?

Which data center did you use for this Lab, im in South Africa, which would be the best datacenter for me to use?

**Comment by polichtm** [comment]
Hi Mohamed,
My deployment was in EastUS…
The parameter “ContosoWebsite.ps1\ContosoWebsite” should be used “as-is” – it is actually with “\\” in the parameter file, but it displays as “\” in the UI. That’s expected

rgds
Marcin

**Comment by polichtm** [comment]
Hi Mohamed
pls advise whether you managed to successfully complete this deployment
Rgds
Marcin

**Comment by MohamedHoosen** [comment]
Hi Marcin, 
Will attempt once again and confirm tomorrow, do apologize, i got side tracked with other stuff, will get back to you, thanks

**Comment by djcmct** [comment]
I think the problem relates to the Image SKU, I have exactly the same problem.
The parameters JSON's both specify 2016-Datacenter, which if unmodified, works perfectly, the instructions in Module 0 task 1 step 11 & Module 0 task 2 step 10  both specify 2016-Datacenter-Server-Core which fails.
I don't think that 2016-Datacenter-Server-Core supports IIS role services required for the deployment.
If the instructions could be modified to reflect the use of 2016-Datacenter as per the parameters JSON then this should avoid any confusion

**Comment by polichtm** [comment]
Updated accordingly
rgds
Marcin
