### ISSUE TITLE
az-101-01b - Install hyper-v labfiles incorrect

### ISSUE THREAD

**Issue by djcmct** [MicrosoftLearning/AZ-101-MicrosoftAzureIntegrationandSecurity#7]
InstallHyperV.ps1 & InstallHyperV.zip used by DSC to install hyper-v & powershell both specify IncludeAllSubFeatures, should be IncludeAllSubFeature - Modified zip attached (not allowed to attach modified .ps1 file) 
I've also included instruction to install hyper v tool as lab uses hyperv manager

[InstallHyperV.zip](https://github.com/MicrosoftLearning/AZ-101-MicrosoftAzureIntegrationandSecurity/files/2915346/InstallHyperV.zip)

**Comment by polichtm** [comment]
resolved
