### ISSUE TITLE
What vesrion should be used for AZ-101

### ISSUE THREAD

**Issue by pdlab** [MicrosoftLearning/AZ-101-MicrosoftAzureIntegrationandSecurity#8]
Are there supposed to be 2 different version of the lab instructions?
Which ones should be used for current AZ-101? or are both required?
Thanks.

**Comment by polichtm** [comment]
These are instructions for the additional set of labs. In short, there are twice as many labs as before (an extra one per module)
rgds
Marcin

**Comment by pdlab** [comment]
Makes sense thank you....  :)

**Comment by polichtm** [comment]
Certainly - np
rgds
Marcin
